// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CoinsColumns holds the columns for the "coins" table.
	CoinsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true},
		{Name: "created_at", Type: field.TypeUint32},
		{Name: "updated_at", Type: field.TypeUint32},
		{Name: "deleted_at", Type: field.TypeUint32},
		{Name: "ent_id", Type: field.TypeUUID, Unique: true},
		{Name: "miningpool_type", Type: field.TypeString},
		{Name: "site", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "coin_type", Type: field.TypeString},
		{Name: "revenue_types", Type: field.TypeJSON, Nullable: true},
		{Name: "fee_rate", Type: field.TypeFloat32, Nullable: true, Default: 0},
		{Name: "fixed_revenue_able", Type: field.TypeBool, Nullable: true, Default: false},
		{Name: "remark", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "threshold", Type: field.TypeFloat32, Nullable: true, Default: 0},
	}
	// CoinsTable holds the schema information for the "coins" table.
	CoinsTable = &schema.Table{
		Name:       "coins",
		Columns:    CoinsColumns,
		PrimaryKey: []*schema.Column{CoinsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "coin_ent_id",
				Unique:  true,
				Columns: []*schema.Column{CoinsColumns[4]},
			},
			{
				Name:    "coin_miningpool_type_coin_type",
				Unique:  true,
				Columns: []*schema.Column{CoinsColumns[5], CoinsColumns[7]},
			},
		},
	}
	// FractionsColumns holds the columns for the "fractions" table.
	FractionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true},
		{Name: "created_at", Type: field.TypeUint32},
		{Name: "updated_at", Type: field.TypeUint32},
		{Name: "deleted_at", Type: field.TypeUint32},
		{Name: "ent_id", Type: field.TypeUUID, Unique: true},
		{Name: "order_user_id", Type: field.TypeUUID},
		{Name: "withdraw_state", Type: field.TypeString},
		{Name: "withdraw_time", Type: field.TypeUint32},
		{Name: "pay_time", Type: field.TypeUint32, Nullable: true},
	}
	// FractionsTable holds the schema information for the "fractions" table.
	FractionsTable = &schema.Table{
		Name:       "fractions",
		Columns:    FractionsColumns,
		PrimaryKey: []*schema.Column{FractionsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "fraction_ent_id",
				Unique:  true,
				Columns: []*schema.Column{FractionsColumns[4]},
			},
		},
	}
	// FractionRulesColumns holds the columns for the "fraction_rules" table.
	FractionRulesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true},
		{Name: "created_at", Type: field.TypeUint32},
		{Name: "updated_at", Type: field.TypeUint32},
		{Name: "deleted_at", Type: field.TypeUint32},
		{Name: "ent_id", Type: field.TypeUUID, Unique: true},
		{Name: "miningpool_type", Type: field.TypeString},
		{Name: "coin_type", Type: field.TypeString},
		{Name: "withdraw_interval", Type: field.TypeUint32},
		{Name: "min_amount", Type: field.TypeFloat32},
		{Name: "withdraw_rate", Type: field.TypeFloat32},
	}
	// FractionRulesTable holds the schema information for the "fraction_rules" table.
	FractionRulesTable = &schema.Table{
		Name:       "fraction_rules",
		Columns:    FractionRulesColumns,
		PrimaryKey: []*schema.Column{FractionRulesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "fractionrule_ent_id",
				Unique:  true,
				Columns: []*schema.Column{FractionRulesColumns[4]},
			},
			{
				Name:    "fractionrule_miningpool_type_coin_type",
				Unique:  true,
				Columns: []*schema.Column{FractionRulesColumns[5], FractionRulesColumns[6]},
			},
		},
	}
	// GoodUsersColumns holds the columns for the "good_users" table.
	GoodUsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true},
		{Name: "created_at", Type: field.TypeUint32},
		{Name: "updated_at", Type: field.TypeUint32},
		{Name: "deleted_at", Type: field.TypeUint32},
		{Name: "ent_id", Type: field.TypeUUID, Unique: true},
		{Name: "good_id", Type: field.TypeUUID},
		{Name: "root_user_id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "miningpool_type", Type: field.TypeString},
		{Name: "coin_type", Type: field.TypeString},
		{Name: "hash_rate", Type: field.TypeFloat32, Nullable: true, Default: 0},
		{Name: "read_page_link", Type: field.TypeString},
		{Name: "revenue_type", Type: field.TypeString},
	}
	// GoodUsersTable holds the schema information for the "good_users" table.
	GoodUsersTable = &schema.Table{
		Name:       "good_users",
		Columns:    GoodUsersColumns,
		PrimaryKey: []*schema.Column{GoodUsersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "gooduser_ent_id",
				Unique:  true,
				Columns: []*schema.Column{GoodUsersColumns[4]},
			},
			{
				Name:    "gooduser_good_id",
				Unique:  false,
				Columns: []*schema.Column{GoodUsersColumns[5]},
			},
			{
				Name:    "gooduser_root_user_id",
				Unique:  false,
				Columns: []*schema.Column{GoodUsersColumns[6]},
			},
			{
				Name:    "gooduser_miningpool_type_coin_type",
				Unique:  false,
				Columns: []*schema.Column{GoodUsersColumns[8], GoodUsersColumns[9]},
			},
		},
	}
	// OrderUsersColumns holds the columns for the "order_users" table.
	OrderUsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true},
		{Name: "created_at", Type: field.TypeUint32},
		{Name: "updated_at", Type: field.TypeUint32},
		{Name: "deleted_at", Type: field.TypeUint32},
		{Name: "ent_id", Type: field.TypeUUID, Unique: true},
		{Name: "root_user_id", Type: field.TypeUUID},
		{Name: "good_user_id", Type: field.TypeUUID},
		{Name: "order_id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "miningpool_type", Type: field.TypeString},
		{Name: "coin_type", Type: field.TypeString},
		{Name: "proportion", Type: field.TypeFloat32, Nullable: true, Default: 0},
		{Name: "revenue_address", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "read_page_link", Type: field.TypeString},
		{Name: "auto_pay", Type: field.TypeBool, Nullable: true, Default: false},
	}
	// OrderUsersTable holds the schema information for the "order_users" table.
	OrderUsersTable = &schema.Table{
		Name:       "order_users",
		Columns:    OrderUsersColumns,
		PrimaryKey: []*schema.Column{OrderUsersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "orderuser_ent_id",
				Unique:  true,
				Columns: []*schema.Column{OrderUsersColumns[4]},
			},
			{
				Name:    "orderuser_order_id",
				Unique:  false,
				Columns: []*schema.Column{OrderUsersColumns[7]},
			},
			{
				Name:    "orderuser_root_user_id",
				Unique:  false,
				Columns: []*schema.Column{OrderUsersColumns[5]},
			},
			{
				Name:    "orderuser_good_user_id",
				Unique:  false,
				Columns: []*schema.Column{OrderUsersColumns[6]},
			},
			{
				Name:    "orderuser_miningpool_type_coin_type",
				Unique:  false,
				Columns: []*schema.Column{OrderUsersColumns[9], OrderUsersColumns[10]},
			},
		},
	}
	// RootUsersColumns holds the columns for the "root_users" table.
	RootUsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true},
		{Name: "created_at", Type: field.TypeUint32},
		{Name: "updated_at", Type: field.TypeUint32},
		{Name: "deleted_at", Type: field.TypeUint32},
		{Name: "ent_id", Type: field.TypeUUID, Unique: true},
		{Name: "name", Type: field.TypeString},
		{Name: "miningpool_type", Type: field.TypeString},
		{Name: "email", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "auth_token", Type: field.TypeString},
		{Name: "authed", Type: field.TypeBool},
		{Name: "remark", Type: field.TypeString, Nullable: true, Default: ""},
	}
	// RootUsersTable holds the schema information for the "root_users" table.
	RootUsersTable = &schema.Table{
		Name:       "root_users",
		Columns:    RootUsersColumns,
		PrimaryKey: []*schema.Column{RootUsersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "rootuser_ent_id",
				Unique:  true,
				Columns: []*schema.Column{RootUsersColumns[4]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CoinsTable,
		FractionsTable,
		FractionRulesTable,
		GoodUsersTable,
		OrderUsersTable,
		RootUsersTable,
	}
)

func init() {
}
