// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/NpoolPlatform/miningpool-middleware/pkg/db/ent/apppool"
	"github.com/google/uuid"
)

// AppPool is the model entity for the AppPool schema.
type AppPool struct {
	config `json:"-"`
	// ID of the ent.
	ID uint32 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt uint32 `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt uint32 `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt uint32 `json:"deleted_at,omitempty"`
	// EntID holds the value of the "ent_id" field.
	EntID uuid.UUID `json:"ent_id,omitempty"`
	// AppID holds the value of the "app_id" field.
	AppID uuid.UUID `json:"app_id,omitempty"`
	// PoolID holds the value of the "pool_id" field.
	PoolID uuid.UUID `json:"pool_id,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AppPool) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case apppool.FieldID, apppool.FieldCreatedAt, apppool.FieldUpdatedAt, apppool.FieldDeletedAt:
			values[i] = new(sql.NullInt64)
		case apppool.FieldEntID, apppool.FieldAppID, apppool.FieldPoolID:
			values[i] = new(uuid.UUID)
		default:
			return nil, fmt.Errorf("unexpected column %q for type AppPool", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AppPool fields.
func (ap *AppPool) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case apppool.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			ap.ID = uint32(value.Int64)
		case apppool.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				ap.CreatedAt = uint32(value.Int64)
			}
		case apppool.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				ap.UpdatedAt = uint32(value.Int64)
			}
		case apppool.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				ap.DeletedAt = uint32(value.Int64)
			}
		case apppool.FieldEntID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field ent_id", values[i])
			} else if value != nil {
				ap.EntID = *value
			}
		case apppool.FieldAppID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field app_id", values[i])
			} else if value != nil {
				ap.AppID = *value
			}
		case apppool.FieldPoolID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field pool_id", values[i])
			} else if value != nil {
				ap.PoolID = *value
			}
		}
	}
	return nil
}

// Update returns a builder for updating this AppPool.
// Note that you need to call AppPool.Unwrap() before calling this method if this AppPool
// was returned from a transaction, and the transaction was committed or rolled back.
func (ap *AppPool) Update() *AppPoolUpdateOne {
	return (&AppPoolClient{config: ap.config}).UpdateOne(ap)
}

// Unwrap unwraps the AppPool entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ap *AppPool) Unwrap() *AppPool {
	_tx, ok := ap.config.driver.(*txDriver)
	if !ok {
		panic("ent: AppPool is not a transactional entity")
	}
	ap.config.driver = _tx.drv
	return ap
}

// String implements the fmt.Stringer.
func (ap *AppPool) String() string {
	var builder strings.Builder
	builder.WriteString("AppPool(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ap.ID))
	builder.WriteString("created_at=")
	builder.WriteString(fmt.Sprintf("%v", ap.CreatedAt))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(fmt.Sprintf("%v", ap.UpdatedAt))
	builder.WriteString(", ")
	builder.WriteString("deleted_at=")
	builder.WriteString(fmt.Sprintf("%v", ap.DeletedAt))
	builder.WriteString(", ")
	builder.WriteString("ent_id=")
	builder.WriteString(fmt.Sprintf("%v", ap.EntID))
	builder.WriteString(", ")
	builder.WriteString("app_id=")
	builder.WriteString(fmt.Sprintf("%v", ap.AppID))
	builder.WriteString(", ")
	builder.WriteString("pool_id=")
	builder.WriteString(fmt.Sprintf("%v", ap.PoolID))
	builder.WriteByte(')')
	return builder.String()
}

// AppPools is a parsable slice of AppPool.
type AppPools []*AppPool

func (ap AppPools) config(cfg config) {
	for _i := range ap {
		ap[_i].config = cfg
	}
}
