// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/miningpool-middleware/pkg/db/ent/gooduser"
	"github.com/NpoolPlatform/miningpool-middleware/pkg/db/ent/predicate"
)

// GoodUserDelete is the builder for deleting a GoodUser entity.
type GoodUserDelete struct {
	config
	hooks    []Hook
	mutation *GoodUserMutation
}

// Where appends a list predicates to the GoodUserDelete builder.
func (gud *GoodUserDelete) Where(ps ...predicate.GoodUser) *GoodUserDelete {
	gud.mutation.Where(ps...)
	return gud
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (gud *GoodUserDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(gud.hooks) == 0 {
		affected, err = gud.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*GoodUserMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			gud.mutation = mutation
			affected, err = gud.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(gud.hooks) - 1; i >= 0; i-- {
			if gud.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = gud.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, gud.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (gud *GoodUserDelete) ExecX(ctx context.Context) int {
	n, err := gud.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (gud *GoodUserDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: gooduser.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint32,
				Column: gooduser.FieldID,
			},
		},
	}
	if ps := gud.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, gud.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// GoodUserDeleteOne is the builder for deleting a single GoodUser entity.
type GoodUserDeleteOne struct {
	gud *GoodUserDelete
}

// Exec executes the deletion query.
func (gudo *GoodUserDeleteOne) Exec(ctx context.Context) error {
	n, err := gudo.gud.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{gooduser.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (gudo *GoodUserDeleteOne) ExecX(ctx context.Context) {
	gudo.gud.ExecX(ctx)
}
