apiVersion: v1
kind: ConfigMap
metadata:
  name: miningpool-middleware-config
  namespace: kube-system
data:
  service-conf: |
    config:
      hostname: "miningpool-middleware.npool.top"
      http_port: 50850
      grpc_port: 50851
      healthz_port: 50852
      prometheus_port: 50853
      appid: "89089012783789789719823798127398"
      serviceid: "52269116-e041-11ee-9d95-5382e1807caf"
      logdir: "./"
      log_level: "warning"
      apolloAccessKey: "0147fb70b815403790e8634b899fac07"
