apiVersion: apps/v1
kind: Deployment
metadata:
  name: miningpool-middleware
  namespace: kube-system
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: miningpool-middleware
  template:
    metadata:
      labels:
        app: miningpool-middleware
    spec:
      containers:
        - name: miningpool-middleware
          image: uhub.service.ucloud.cn/entropypool/miningpool-middleware:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: service-config
              mountPath: /etc/MiningpoolMiddleware
          env:
            - name: ENV_ENVIRONMENT_TARGET
              valueFrom:
                configMapKeyRef:
                  name: system-environment
                  key: environment.target
            - name: ENV_CONSUL_HOST
              valueFrom:
                configMapKeyRef:
                  name: system-environment
                  key: environment.consul_host
            - name: ENV_CONSUL_PORT
              valueFrom:
                configMapKeyRef:
                  name: system-environment
                  key: environment.consul_port
            - name: ENV_CLUSTER_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      volumes:
        - name: service-config
          configMap:
            name: miningpool-middleware-config
            items:
              - key: service-conf
                path: MiningpoolMiddleware.viper.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: miningpool-middleware
  namespace: kube-system
spec:
  ports:
    - name: http
      port: 50850
      targetPort: 50850
    - name: grpc
      port: 50851
      targetPort: 50851
    - name: healthz
      port: 50852
      targetPort: 50852
    - name: prometheus
      port: 50853
      targetPort: 50853
  selector:
    app: miningpool-middleware
