apiVersion: traefik.containo.us/v1
kind: Middleware
metadata:
  name: strip-miningpool-middleware-prefix
  namespace: kube-system
spec:
  stripPrefix:
    prefixes:
      - /api/miningpool-middleware
