// Code generated by ent, DO NOT EDIT.

package fractionwithdrawalrule

import (
	"entgo.io/ent/dialect/sql"
	"github.com/NpoolPlatform/miningpool-middleware/pkg/db/ent/predicate"
	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

// ID filters vertices based on their ID field.
func ID(id uint32) predicate.FractionWithdrawalRule {
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint32) predicate.FractionWithdrawalRule {
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint32) predicate.FractionWithdrawalRule {
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint32) predicate.FractionWithdrawalRule {
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint32) predicate.FractionWithdrawalRule {
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint32) predicate.FractionWithdrawalRule {
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint32) predicate.FractionWithdrawalRule {
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint32) predicate.FractionWithdrawalRule {
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint32) predicate.FractionWithdrawalRule {
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v uint32) predicate.FractionWithdrawalRule {
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCreatedAt), v))
	})
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v uint32) predicate.FractionWithdrawalRule {
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUpdatedAt), v))
	})
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v uint32) predicate.FractionWithdrawalRule {
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldDeletedAt), v))
	})
}

// EntID applies equality check predicate on the "ent_id" field. It's identical to EntIDEQ.
func EntID(v uuid.UUID) predicate.FractionWithdrawalRule {
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldEntID), v))
	})
}

// PoolCoinTypeID applies equality check predicate on the "pool_coin_type_id" field. It's identical to PoolCoinTypeIDEQ.
func PoolCoinTypeID(v uuid.UUID) predicate.FractionWithdrawalRule {
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldPoolCoinTypeID), v))
	})
}

// WithdrawInterval applies equality check predicate on the "withdraw_interval" field. It's identical to WithdrawIntervalEQ.
func WithdrawInterval(v uint32) predicate.FractionWithdrawalRule {
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldWithdrawInterval), v))
	})
}

// LeastWithdrawalAmount applies equality check predicate on the "least_withdrawal_amount" field. It's identical to LeastWithdrawalAmountEQ.
func LeastWithdrawalAmount(v decimal.Decimal) predicate.FractionWithdrawalRule {
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldLeastWithdrawalAmount), v))
	})
}

// PayoutThreshold applies equality check predicate on the "payout_threshold" field. It's identical to PayoutThresholdEQ.
func PayoutThreshold(v decimal.Decimal) predicate.FractionWithdrawalRule {
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldPayoutThreshold), v))
	})
}

// WithdrawFee applies equality check predicate on the "withdraw_fee" field. It's identical to WithdrawFeeEQ.
func WithdrawFee(v decimal.Decimal) predicate.FractionWithdrawalRule {
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldWithdrawFee), v))
	})
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v uint32) predicate.FractionWithdrawalRule {
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v uint32) predicate.FractionWithdrawalRule {
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...uint32) predicate.FractionWithdrawalRule {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldCreatedAt), v...))
	})
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...uint32) predicate.FractionWithdrawalRule {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldCreatedAt), v...))
	})
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v uint32) predicate.FractionWithdrawalRule {
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v uint32) predicate.FractionWithdrawalRule {
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v uint32) predicate.FractionWithdrawalRule {
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v uint32) predicate.FractionWithdrawalRule {
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldCreatedAt), v))
	})
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v uint32) predicate.FractionWithdrawalRule {
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v uint32) predicate.FractionWithdrawalRule {
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...uint32) predicate.FractionWithdrawalRule {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldUpdatedAt), v...))
	})
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...uint32) predicate.FractionWithdrawalRule {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldUpdatedAt), v...))
	})
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v uint32) predicate.FractionWithdrawalRule {
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v uint32) predicate.FractionWithdrawalRule {
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v uint32) predicate.FractionWithdrawalRule {
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v uint32) predicate.FractionWithdrawalRule {
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldUpdatedAt), v))
	})
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v uint32) predicate.FractionWithdrawalRule {
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldDeletedAt), v))
	})
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v uint32) predicate.FractionWithdrawalRule {
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldDeletedAt), v))
	})
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...uint32) predicate.FractionWithdrawalRule {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldDeletedAt), v...))
	})
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...uint32) predicate.FractionWithdrawalRule {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldDeletedAt), v...))
	})
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v uint32) predicate.FractionWithdrawalRule {
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldDeletedAt), v))
	})
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v uint32) predicate.FractionWithdrawalRule {
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldDeletedAt), v))
	})
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v uint32) predicate.FractionWithdrawalRule {
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldDeletedAt), v))
	})
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v uint32) predicate.FractionWithdrawalRule {
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldDeletedAt), v))
	})
}

// EntIDEQ applies the EQ predicate on the "ent_id" field.
func EntIDEQ(v uuid.UUID) predicate.FractionWithdrawalRule {
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldEntID), v))
	})
}

// EntIDNEQ applies the NEQ predicate on the "ent_id" field.
func EntIDNEQ(v uuid.UUID) predicate.FractionWithdrawalRule {
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldEntID), v))
	})
}

// EntIDIn applies the In predicate on the "ent_id" field.
func EntIDIn(vs ...uuid.UUID) predicate.FractionWithdrawalRule {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldEntID), v...))
	})
}

// EntIDNotIn applies the NotIn predicate on the "ent_id" field.
func EntIDNotIn(vs ...uuid.UUID) predicate.FractionWithdrawalRule {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldEntID), v...))
	})
}

// EntIDGT applies the GT predicate on the "ent_id" field.
func EntIDGT(v uuid.UUID) predicate.FractionWithdrawalRule {
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldEntID), v))
	})
}

// EntIDGTE applies the GTE predicate on the "ent_id" field.
func EntIDGTE(v uuid.UUID) predicate.FractionWithdrawalRule {
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldEntID), v))
	})
}

// EntIDLT applies the LT predicate on the "ent_id" field.
func EntIDLT(v uuid.UUID) predicate.FractionWithdrawalRule {
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldEntID), v))
	})
}

// EntIDLTE applies the LTE predicate on the "ent_id" field.
func EntIDLTE(v uuid.UUID) predicate.FractionWithdrawalRule {
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldEntID), v))
	})
}

// PoolCoinTypeIDEQ applies the EQ predicate on the "pool_coin_type_id" field.
func PoolCoinTypeIDEQ(v uuid.UUID) predicate.FractionWithdrawalRule {
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldPoolCoinTypeID), v))
	})
}

// PoolCoinTypeIDNEQ applies the NEQ predicate on the "pool_coin_type_id" field.
func PoolCoinTypeIDNEQ(v uuid.UUID) predicate.FractionWithdrawalRule {
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldPoolCoinTypeID), v))
	})
}

// PoolCoinTypeIDIn applies the In predicate on the "pool_coin_type_id" field.
func PoolCoinTypeIDIn(vs ...uuid.UUID) predicate.FractionWithdrawalRule {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldPoolCoinTypeID), v...))
	})
}

// PoolCoinTypeIDNotIn applies the NotIn predicate on the "pool_coin_type_id" field.
func PoolCoinTypeIDNotIn(vs ...uuid.UUID) predicate.FractionWithdrawalRule {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldPoolCoinTypeID), v...))
	})
}

// PoolCoinTypeIDGT applies the GT predicate on the "pool_coin_type_id" field.
func PoolCoinTypeIDGT(v uuid.UUID) predicate.FractionWithdrawalRule {
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldPoolCoinTypeID), v))
	})
}

// PoolCoinTypeIDGTE applies the GTE predicate on the "pool_coin_type_id" field.
func PoolCoinTypeIDGTE(v uuid.UUID) predicate.FractionWithdrawalRule {
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldPoolCoinTypeID), v))
	})
}

// PoolCoinTypeIDLT applies the LT predicate on the "pool_coin_type_id" field.
func PoolCoinTypeIDLT(v uuid.UUID) predicate.FractionWithdrawalRule {
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldPoolCoinTypeID), v))
	})
}

// PoolCoinTypeIDLTE applies the LTE predicate on the "pool_coin_type_id" field.
func PoolCoinTypeIDLTE(v uuid.UUID) predicate.FractionWithdrawalRule {
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldPoolCoinTypeID), v))
	})
}

// PoolCoinTypeIDIsNil applies the IsNil predicate on the "pool_coin_type_id" field.
func PoolCoinTypeIDIsNil() predicate.FractionWithdrawalRule {
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldPoolCoinTypeID)))
	})
}

// PoolCoinTypeIDNotNil applies the NotNil predicate on the "pool_coin_type_id" field.
func PoolCoinTypeIDNotNil() predicate.FractionWithdrawalRule {
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldPoolCoinTypeID)))
	})
}

// WithdrawIntervalEQ applies the EQ predicate on the "withdraw_interval" field.
func WithdrawIntervalEQ(v uint32) predicate.FractionWithdrawalRule {
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldWithdrawInterval), v))
	})
}

// WithdrawIntervalNEQ applies the NEQ predicate on the "withdraw_interval" field.
func WithdrawIntervalNEQ(v uint32) predicate.FractionWithdrawalRule {
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldWithdrawInterval), v))
	})
}

// WithdrawIntervalIn applies the In predicate on the "withdraw_interval" field.
func WithdrawIntervalIn(vs ...uint32) predicate.FractionWithdrawalRule {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldWithdrawInterval), v...))
	})
}

// WithdrawIntervalNotIn applies the NotIn predicate on the "withdraw_interval" field.
func WithdrawIntervalNotIn(vs ...uint32) predicate.FractionWithdrawalRule {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldWithdrawInterval), v...))
	})
}

// WithdrawIntervalGT applies the GT predicate on the "withdraw_interval" field.
func WithdrawIntervalGT(v uint32) predicate.FractionWithdrawalRule {
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldWithdrawInterval), v))
	})
}

// WithdrawIntervalGTE applies the GTE predicate on the "withdraw_interval" field.
func WithdrawIntervalGTE(v uint32) predicate.FractionWithdrawalRule {
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldWithdrawInterval), v))
	})
}

// WithdrawIntervalLT applies the LT predicate on the "withdraw_interval" field.
func WithdrawIntervalLT(v uint32) predicate.FractionWithdrawalRule {
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldWithdrawInterval), v))
	})
}

// WithdrawIntervalLTE applies the LTE predicate on the "withdraw_interval" field.
func WithdrawIntervalLTE(v uint32) predicate.FractionWithdrawalRule {
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldWithdrawInterval), v))
	})
}

// WithdrawIntervalIsNil applies the IsNil predicate on the "withdraw_interval" field.
func WithdrawIntervalIsNil() predicate.FractionWithdrawalRule {
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldWithdrawInterval)))
	})
}

// WithdrawIntervalNotNil applies the NotNil predicate on the "withdraw_interval" field.
func WithdrawIntervalNotNil() predicate.FractionWithdrawalRule {
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldWithdrawInterval)))
	})
}

// LeastWithdrawalAmountEQ applies the EQ predicate on the "least_withdrawal_amount" field.
func LeastWithdrawalAmountEQ(v decimal.Decimal) predicate.FractionWithdrawalRule {
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldLeastWithdrawalAmount), v))
	})
}

// LeastWithdrawalAmountNEQ applies the NEQ predicate on the "least_withdrawal_amount" field.
func LeastWithdrawalAmountNEQ(v decimal.Decimal) predicate.FractionWithdrawalRule {
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldLeastWithdrawalAmount), v))
	})
}

// LeastWithdrawalAmountIn applies the In predicate on the "least_withdrawal_amount" field.
func LeastWithdrawalAmountIn(vs ...decimal.Decimal) predicate.FractionWithdrawalRule {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldLeastWithdrawalAmount), v...))
	})
}

// LeastWithdrawalAmountNotIn applies the NotIn predicate on the "least_withdrawal_amount" field.
func LeastWithdrawalAmountNotIn(vs ...decimal.Decimal) predicate.FractionWithdrawalRule {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldLeastWithdrawalAmount), v...))
	})
}

// LeastWithdrawalAmountGT applies the GT predicate on the "least_withdrawal_amount" field.
func LeastWithdrawalAmountGT(v decimal.Decimal) predicate.FractionWithdrawalRule {
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldLeastWithdrawalAmount), v))
	})
}

// LeastWithdrawalAmountGTE applies the GTE predicate on the "least_withdrawal_amount" field.
func LeastWithdrawalAmountGTE(v decimal.Decimal) predicate.FractionWithdrawalRule {
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldLeastWithdrawalAmount), v))
	})
}

// LeastWithdrawalAmountLT applies the LT predicate on the "least_withdrawal_amount" field.
func LeastWithdrawalAmountLT(v decimal.Decimal) predicate.FractionWithdrawalRule {
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldLeastWithdrawalAmount), v))
	})
}

// LeastWithdrawalAmountLTE applies the LTE predicate on the "least_withdrawal_amount" field.
func LeastWithdrawalAmountLTE(v decimal.Decimal) predicate.FractionWithdrawalRule {
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldLeastWithdrawalAmount), v))
	})
}

// LeastWithdrawalAmountIsNil applies the IsNil predicate on the "least_withdrawal_amount" field.
func LeastWithdrawalAmountIsNil() predicate.FractionWithdrawalRule {
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldLeastWithdrawalAmount)))
	})
}

// LeastWithdrawalAmountNotNil applies the NotNil predicate on the "least_withdrawal_amount" field.
func LeastWithdrawalAmountNotNil() predicate.FractionWithdrawalRule {
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldLeastWithdrawalAmount)))
	})
}

// PayoutThresholdEQ applies the EQ predicate on the "payout_threshold" field.
func PayoutThresholdEQ(v decimal.Decimal) predicate.FractionWithdrawalRule {
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldPayoutThreshold), v))
	})
}

// PayoutThresholdNEQ applies the NEQ predicate on the "payout_threshold" field.
func PayoutThresholdNEQ(v decimal.Decimal) predicate.FractionWithdrawalRule {
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldPayoutThreshold), v))
	})
}

// PayoutThresholdIn applies the In predicate on the "payout_threshold" field.
func PayoutThresholdIn(vs ...decimal.Decimal) predicate.FractionWithdrawalRule {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldPayoutThreshold), v...))
	})
}

// PayoutThresholdNotIn applies the NotIn predicate on the "payout_threshold" field.
func PayoutThresholdNotIn(vs ...decimal.Decimal) predicate.FractionWithdrawalRule {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldPayoutThreshold), v...))
	})
}

// PayoutThresholdGT applies the GT predicate on the "payout_threshold" field.
func PayoutThresholdGT(v decimal.Decimal) predicate.FractionWithdrawalRule {
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldPayoutThreshold), v))
	})
}

// PayoutThresholdGTE applies the GTE predicate on the "payout_threshold" field.
func PayoutThresholdGTE(v decimal.Decimal) predicate.FractionWithdrawalRule {
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldPayoutThreshold), v))
	})
}

// PayoutThresholdLT applies the LT predicate on the "payout_threshold" field.
func PayoutThresholdLT(v decimal.Decimal) predicate.FractionWithdrawalRule {
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldPayoutThreshold), v))
	})
}

// PayoutThresholdLTE applies the LTE predicate on the "payout_threshold" field.
func PayoutThresholdLTE(v decimal.Decimal) predicate.FractionWithdrawalRule {
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldPayoutThreshold), v))
	})
}

// PayoutThresholdIsNil applies the IsNil predicate on the "payout_threshold" field.
func PayoutThresholdIsNil() predicate.FractionWithdrawalRule {
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldPayoutThreshold)))
	})
}

// PayoutThresholdNotNil applies the NotNil predicate on the "payout_threshold" field.
func PayoutThresholdNotNil() predicate.FractionWithdrawalRule {
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldPayoutThreshold)))
	})
}

// WithdrawFeeEQ applies the EQ predicate on the "withdraw_fee" field.
func WithdrawFeeEQ(v decimal.Decimal) predicate.FractionWithdrawalRule {
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldWithdrawFee), v))
	})
}

// WithdrawFeeNEQ applies the NEQ predicate on the "withdraw_fee" field.
func WithdrawFeeNEQ(v decimal.Decimal) predicate.FractionWithdrawalRule {
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldWithdrawFee), v))
	})
}

// WithdrawFeeIn applies the In predicate on the "withdraw_fee" field.
func WithdrawFeeIn(vs ...decimal.Decimal) predicate.FractionWithdrawalRule {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.In(s.C(FieldWithdrawFee), v...))
	})
}

// WithdrawFeeNotIn applies the NotIn predicate on the "withdraw_fee" field.
func WithdrawFeeNotIn(vs ...decimal.Decimal) predicate.FractionWithdrawalRule {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.NotIn(s.C(FieldWithdrawFee), v...))
	})
}

// WithdrawFeeGT applies the GT predicate on the "withdraw_fee" field.
func WithdrawFeeGT(v decimal.Decimal) predicate.FractionWithdrawalRule {
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldWithdrawFee), v))
	})
}

// WithdrawFeeGTE applies the GTE predicate on the "withdraw_fee" field.
func WithdrawFeeGTE(v decimal.Decimal) predicate.FractionWithdrawalRule {
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldWithdrawFee), v))
	})
}

// WithdrawFeeLT applies the LT predicate on the "withdraw_fee" field.
func WithdrawFeeLT(v decimal.Decimal) predicate.FractionWithdrawalRule {
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldWithdrawFee), v))
	})
}

// WithdrawFeeLTE applies the LTE predicate on the "withdraw_fee" field.
func WithdrawFeeLTE(v decimal.Decimal) predicate.FractionWithdrawalRule {
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldWithdrawFee), v))
	})
}

// WithdrawFeeIsNil applies the IsNil predicate on the "withdraw_fee" field.
func WithdrawFeeIsNil() predicate.FractionWithdrawalRule {
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldWithdrawFee)))
	})
}

// WithdrawFeeNotNil applies the NotNil predicate on the "withdraw_fee" field.
func WithdrawFeeNotNil() predicate.FractionWithdrawalRule {
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldWithdrawFee)))
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.FractionWithdrawalRule) predicate.FractionWithdrawalRule {
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.FractionWithdrawalRule) predicate.FractionWithdrawalRule {
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.FractionWithdrawalRule) predicate.FractionWithdrawalRule {
	return predicate.FractionWithdrawalRule(func(s *sql.Selector) {
		p(s.Not())
	})
}
