// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AppPool is the predicate function for apppool builders.
type AppPool func(*sql.Selector)

// Coin is the predicate function for coin builders.
type Coin func(*sql.Selector)

// FractionWithdrawal is the predicate function for fractionwithdrawal builders.
type FractionWithdrawal func(*sql.Selector)

// FractionWithdrawalRule is the predicate function for fractionwithdrawalrule builders.
type FractionWithdrawalRule func(*sql.Selector)

// GoodUser is the predicate function for gooduser builders.
type GoodUser func(*sql.Selector)

// OrderUser is the predicate function for orderuser builders.
type OrderUser func(*sql.Selector)

// Pool is the predicate function for pool builders.
type Pool func(*sql.Selector)

// RootUser is the predicate function for rootuser builders.
type RootUser func(*sql.Selector)
