// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Coin is the predicate function for coin builders.
type Coin func(*sql.Selector)

// Fraction is the predicate function for fraction builders.
type Fraction func(*sql.Selector)

// FractionRule is the predicate function for fractionrule builders.
type FractionRule func(*sql.Selector)

// GoodUser is the predicate function for gooduser builders.
type GoodUser func(*sql.Selector)

// OrderUser is the predicate function for orderuser builders.
type OrderUser func(*sql.Selector)

// RootUser is the predicate function for rootuser builders.
type RootUser func(*sql.Selector)
